name: Deploy documentation

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

jobs:
  docdeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.3.1
      - uses: julia-actions/julia-docdeploy@releases/v1
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
